wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714798918.716002
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.10.6
      5: 0.15.5
      6: 4.38.2
      8:
      - 8
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 5.0e-05
model_max_length:
  desc: null
  value: 512
